name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    name: "Validate Lab"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lab:
          - secure-static-web-hosting

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init & Validate
        run: |
          cd ${{ matrix.lab }}
          terraform init -backend=false
          terraform validate